-- ============================================================================
-- A small, invented LabStack — enough for every Atlas page to have something
-- to show.
--
-- None of this is real. The cities, their coordinates and the pincode ranges
-- are public geography; every lab, doctor, patient, order and price below was
-- generated by the SQL in this file. No LabStack data is in this repository
-- and none should ever be committed to it — if you need real data locally,
-- point at the source database instead (docs/LOCAL-SETUP.md).
--
-- Deterministic: setseed() fixes the sequence, so two developers running this
-- get the same rows and can compare numbers with each other.
--
-- Re-runnable: truncates before it inserts.
-- ============================================================================

SET search_path = src_local, public;

-- One transaction: the temp tables below are ON COMMIT DROP, and psql commits
-- after every statement unless told otherwise — without this the first temp
-- table is gone before the insert that fills it.
BEGIN;
SELECT setseed(0.42);

TRUNCATE "Lab", "Chain", "Provider", "ProviderType", "Pharmacy", "Store",
         "PincodeToLatLong", "User", "Profile", "Order", "Request",
         "Master", "Package", "PackagesOnLab", "DOS", "_MasterToPackage",
         "_MasterToRequest", "_PackageToRequest", "PackagesOnStore",
         "LabsOnStore", "Appointment", "PharmaOrder";

-- ---------------------------------------------------------------------------
-- Geography. Ten real cities, a made-up block of pincodes around each.
--
-- Two metros, two large cities and six smaller ones, because the readiness and
-- tiering pages exist to tell those apart and a seed of ten metros would make
-- every one of them say the same thing.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE city_anchor (city text, state text, pin_base int, lat float, lng float, labs int) ON COMMIT DROP;
INSERT INTO city_anchor VALUES
  ('Mumbai',    'Maharashtra',    400001, 19.0760, 72.8777, 9),
  ('Delhi',     'Delhi',          110001, 28.6139, 77.2090, 8),
  ('Bengaluru', 'Karnataka',      560001, 12.9716, 77.5946, 7),
  ('Pune',      'Maharashtra',    411001, 18.5204, 73.8567, 5),
  ('Hyderabad', 'Telangana',      500001, 17.3850, 78.4867, 5),
  ('Jaipur',    'Rajasthan',      302001, 26.9124, 75.7873, 3),
  ('Indore',    'Madhya Pradesh', 452001, 22.7196, 75.8577, 3),
  ('Kochi',     'Kerala',         682001, 9.9312,  76.2673, 2),
  ('Guwahati',  'Assam',          781001, 26.1445, 91.7362, 2),
  ('Nagpur',    'Maharashtra',    440001, 21.1458, 79.0882, 2);

-- Eight pincodes per city, spread over roughly 12 km.
INSERT INTO "PincodeToLatLong" (id, pincode, latitude, longitude, city, state, district)
SELECT row_number() OVER ()::int,
       lpad((a.pin_base + g)::text, 6, '0'),
       a.lat + (g - 4) * 0.012,
       a.lng + (g - 4) * 0.013,
       a.city, a.state, a.city
FROM city_anchor a, generate_series(0, 7) g;

-- ---------------------------------------------------------------------------
-- Chains and labs.
-- ---------------------------------------------------------------------------
INSERT INTO "Chain" (id, "chainName", name, "createdAt", "updatedAt") VALUES
  (1, 'Northwind Diagnostics', 'Northwind Diagnostics', now() - interval '3 years', now()),
  (2, 'Silverleaf Labs',       'Silverleaf Labs',       now() - interval '2 years', now()),
  (3, 'Cedarcare Group',       'Cedarcare Group',       now() - interval '18 months', now()),
  (4, 'Bluewater Health',      'Bluewater Health',      now() - interval '1 year', now());

CREATE TEMP TABLE lab_word (w text) ON COMMIT DROP;
INSERT INTO lab_word VALUES ('Northwind'),('Silverleaf'),('Cedarcare'),('Bluewater'),
  ('Greenfield'),('Harbour'),('Summit'),('Orchid'),('Lakeside'),('Ironbridge'),
  ('Meadow'),('Redstone'),('Kingfisher'),('Amberton'),('Fairview');

WITH numbered AS (
  SELECT a.*, generate_series(1, a.labs) AS n,
         row_number() OVER (ORDER BY a.city, generate_series(1, a.labs)) AS id
  FROM city_anchor a
)
INSERT INTO "Lab" (
  id, "labName", "centerType", chain_id, address, locality, city, state, pincode,
  active, latitude, longitude, "pincodesServiced", "homeCollection", "centerVisit",
  "createdAt", "updatedAt", "labCenterEmail", "labCenterMobile", "gstNumber",
  "mouStartDate", "mouEndDate"
)
SELECT
  n.id,
  (SELECT w FROM lab_word ORDER BY (n.id * 7 + n.n) % 15 LIMIT 1)
    || CASE n.n % 3 WHEN 0 THEN ' Diagnostics' WHEN 1 THEN ' Path Lab' ELSE ' Health Centre' END
    || ' · ' || n.city,
  (ARRAY['DIAGNOSTIC_CENTER','COLLECTION_CENTER','HOSPITAL']::"CenterType"[])[1 + (n.n % 3)],
  CASE WHEN n.n % 4 = 0 THEN 1 + (n.id % 4) ELSE NULL END,
  n.n || ', Sample Road', 'Block ' || chr(65 + (n.n % 6)), n.city, n.state,
  lpad((n.pin_base + (n.n % 8))::text, 6, '0'),
  true,
  n.lat + ((n.n % 8) - 4) * 0.012 + (random() - 0.5) * 0.004,
  n.lng + ((n.n % 8) - 4) * 0.013 + (random() - 0.5) * 0.004,
  -- Home collection reaches a handful of nearby pincodes; a centre-only lab
  -- serves none, which is what makes the two coverage numbers differ.
  CASE WHEN n.n % 4 <> 3
       THEN (SELECT array_agg(lpad((n.pin_base + g)::text, 6, '0'))
               FROM generate_series(0, 7) g WHERE g <= 3 + (n.n % 4))
       ELSE NULL END,
  (n.n % 4 <> 3),
  (n.n % 5 <> 4),
  now() - ((n.id * 13) || ' days')::interval,
  now() - ((n.id) || ' days')::interval,
  'ops' || n.id || '@example.test',
  '90000' || lpad(n.id::text, 5, '0'),
  '27AAAAA' || lpad(n.id::text, 4, '0') || 'A1Z5',
  now() - interval '1 year', now() + interval '1 year'
FROM numbered n;

-- ---------------------------------------------------------------------------
-- Providers: the people, not the buildings.
-- ---------------------------------------------------------------------------
INSERT INTO "ProviderType" (id, "typeName") VALUES
  (1, 'Doctor'), (2, 'Phlebotomist'), (3, 'Nurse'), (4, 'Physiotherapist');

INSERT INTO "Provider" (id, name, "typeId", address, locality, city, state, pincode,
                        latitude, longitude, mobile, email, "registrationBody",
                        "registrationNum", "isVerified", "experienceStart",
                        active, "createdAt", "updatedAt")
SELECT g,
       (ARRAY['Dr. A. Menon','Dr. S. Iyer','Dr. R. Bose','P. Kulkarni','N. Sharma',
              'V. Das','M. Pillai','K. Reddy','J. Fernandes','T. Ahuja'])[1 + (g % 10)]
         || ' (' || g || ')',
       1 + (g % 4),
       g || ', Clinic Lane', 'Sector ' || (1 + g % 9), a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       a.lat + ((g % 8) - 4) * 0.012, a.lng + ((g % 8) - 4) * 0.013,
       '98000' || lpad(g::text, 5, '0'), 'provider' || g || '@example.test',
       CASE WHEN g % 4 <> 0 THEN 'State Council' END,
       CASE WHEN g % 4 <> 0 THEN 'REG-' || lpad(g::text, 5, '0') END,
       (g % 3 <> 0),
       now() - ((3 + (g % 15)) || ' years')::interval,
       true, now() - ((g * 5) || ' days')::interval, now()
FROM generate_series(1, 60) g
CROSS JOIN LATERAL (
  SELECT * FROM city_anchor ORDER BY (g * 31) % 10 LIMIT 1 OFFSET (g % 10)
) a;

INSERT INTO "Pharmacy" (id, name, address, city, state, pincode, latitude, longitude,
                        active, "createdAt", "updatedAt")
SELECT g,
       (ARRAY['Wellspring','Cornerstone','Gracewell','Apex','Sunrise'])[1 + (g % 5)] || ' Pharmacy ' || g,
       g || ', Market Street', a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       a.lat + ((g % 8) - 4) * 0.012, a.lng + ((g % 8) - 4) * 0.013,
       true, now() - ((g * 9) || ' days')::interval, now()
FROM generate_series(1, 14) g
CROSS JOIN LATERAL (SELECT * FROM city_anchor ORDER BY (g * 17) % 10 LIMIT 1 OFFSET (g % 10)) a;

-- ---------------------------------------------------------------------------
-- Stores: the B2B partners orders arrive from.
-- ---------------------------------------------------------------------------
-- Ten, not eight, and the last two earn their place: store 9 is active with no
-- orders at all and store 10 is closed. Both are states the stores screen has
-- to render — an empty partner must not look like a broken query, and a closed
-- one must stay reachable for the orders it left behind — and with eight
-- identical busy stores neither was ever exercised.
INSERT INTO "Store" (id, "storeName", "legalName", "storeType", address, locality, city, state,
                     pincode, active, "apiEnabled", "createdAt", "updatedAt", "isDoctor", pocs)
SELECT g,
       (ARRAY['Riverbend Clinic','Parkview Polyclinic','Trailhead Wellness','Stonegate Care',
              'Maple Health','Eastfield Clinic','Fernway Medical','Harbourside Care',
              'Willowmere Health','Oldgate Clinic'])[g],
       (ARRAY['Riverbend','Parkview','Trailhead','Stonegate','Maple','Eastfield','Fernway',
              'Harbourside','Willowmere','Oldgate'])[g] || ' Pvt Ltd',
       CASE WHEN g % 3 = 0 THEN 'CLINIC' ELSE 'CORPORATE' END,
       g || ', Partner Avenue', 'Phase ' || g, a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       (g <> 10), (g % 2 = 0), now() - ((g * 40) || ' days')::interval, now(), (g % 3 = 0),
       -- One point of contact each. The console stores these as an array of
       -- objects; the stores screen reads the first.
       ARRAY[jsonb_build_object(
         'name',  (ARRAY['Asha','Vikram','Meera','Joseph','Nandini','Rahul','Farah','Dev',
                         'Ila','Samir'])[g] || ' ' ||
                  (ARRAY['Rao','Nair','Sen','Mathew','Kulkarni','Bose','Sheikh','Menon',
                         'Chawla','Iyer'])[g],
         'phone', '98' || lpad((1000000 + g * 37)::text, 8, '0'),
         'email', 'ops@' || lower((ARRAY['riverbend','parkview','trailhead','stonegate','maple',
                                         'eastfield','fernway','harbourside','willowmere',
                                         'oldgate'])[g]) || '.example.test')]
FROM generate_series(1, 10) g
CROSS JOIN LATERAL (SELECT * FROM city_anchor ORDER BY (g * 23) % 10 LIMIT 1 OFFSET (g % 10)) a;

-- ---------------------------------------------------------------------------
-- Patients. A user and the profile carrying the address an order is served at.
-- ---------------------------------------------------------------------------
INSERT INTO "User" (id, email, phone, name, "createdAt", "updatedAt")
SELECT g, 'patient' || g || '@example.test', '99000' || lpad(g::text, 5, '0'),
       'Patient ' || g, now() - ((g % 500) || ' days')::interval, now()
FROM generate_series(1, 400) g;

INSERT INTO "Profile" (id, "profileUserId", name, gender, dob, address, locality, city, state,
                       pincode, latitude, longitude, "createdAt", "updatedAt")
SELECT g, g, 'Patient ' || g,
       (ARRAY['MALE','FEMALE','OTHERS']::"Gender"[])[1 + (g % 3)],
       now() - ((20 + (g % 50)) || ' years')::interval,
       g || ', Residency Road', 'Ward ' || (1 + g % 12), a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       -- Scattered around the pincode, because the geo rebuild takes the
       -- median of the addresses it has seen there.
       a.lat + ((g % 8) - 4) * 0.012 + (random() - 0.5) * 0.006,
       a.lng + ((g % 8) - 4) * 0.013 + (random() - 0.5) * 0.006,
       now() - ((g % 500) || ' days')::interval, now()
FROM generate_series(1, 400) g
CROSS JOIN LATERAL (SELECT * FROM city_anchor ORDER BY (g * 11) % 10 LIMIT 1 OFFSET (g % 10)) a;

-- ---------------------------------------------------------------------------
-- Orders across the last year, weighted the way a real book is: mostly home
-- collection, mostly delivered, a tail of cancellations.
-- ---------------------------------------------------------------------------
-- Weighted by city, because a leaderboard where every city has the same number
-- is no test of a leaderboard. Roughly six orders in Mumbai for every one in
-- Guwahati, which is the shape of the real book.
CREATE TEMP TABLE city_weight (city text, w int) ON COMMIT DROP;
INSERT INTO city_weight VALUES
  ('Mumbai', 6), ('Delhi', 5), ('Bengaluru', 5), ('Hyderabad', 4), ('Pune', 3),
  ('Jaipur', 2), ('Indore', 2), ('Kochi', 2), ('Nagpur', 1), ('Guwahati', 1);

-- Twenty-one slots rather than seven, because the stores screen groups orders
-- into six stages and the old seed only ever produced four of them: nothing
-- was pending, nothing had been rescheduled, nobody had missed an
-- appointment, and no order had a phlebo on it. Every one of those is a
-- column somebody reads, and a column that is always empty is a feature
-- nobody can check.
--
-- The proportions are held to what they were. Delivered is 9 of 21 against 3
-- of 7 — the same 43% — and the scheduled and in-flight shares move by less
-- than five points, so the leaderboard, the coverage views and the lab
-- history that read this table keep the book shape they were built against.
--
-- Twenty-one and not twenty: orderType cycles every 5, and any array length
-- divisible by 5 locks the two together, so every pending order would have
-- been a CENTER_VISIT. Coprime lengths keep them independent.
INSERT INTO "Order" (id, "orderType", "orderStatus", "storeId", "labId", "userId",
                     "createdAt", "updatedAt", "appointmentTime", "statusUpdatedAt",
                     "isPostpaid", source, "referenceId",
                     "phleboName", "phleboNumber", "assignedAt", "assignedBy",
                     "cancelReason")
SELECT x.k,
       t.order_type,
       s.status,
       1 + (x.k % 8),
       -- Served by a lab in the same city where there is one, which is what
       -- makes the coverage and imbalance views say anything at all.
       COALESCE(
         (SELECT l.id FROM "Lab" l WHERE l.city = x.city ORDER BY (l.id + x.k) % 97 LIMIT 1),
         1 + (x.k % 40)),
       x.uid,
       d.created_at,
       d.created_at,
       d.appointment_at,
       d.status_at,
       (x.k % 4 = 0),
       'STORE_API'::"Source",
       -- The store's own reference, which is what a partner quotes on a call
       -- and therefore what the stores screen has to be searchable by.
       'ST' || lpad((1 + (x.k % 8))::text, 2, '0') || '-' || lpad(x.k::text, 6, '0'),
       ph.name, ph.phone, ph.assigned_at, ph.assigned_by,
       CASE WHEN s.status IN ('CANCELED', 'PATIENT_MISSED')
            THEN (ARRAY['Patient unavailable','Duplicate order','Booked elsewhere',
                        'Patient declined','Address unreachable','Sample rejected'])[1 + (x.k % 6)]
       END
FROM (
  SELECT p."profileUserId" AS uid, p.city,
         row_number() OVER (ORDER BY p.id, g) AS k
  FROM "Profile" p
  JOIN city_weight w ON w.city = p.city
  CROSS JOIN LATERAL generate_series(1, w.w) g
) x
CROSS JOIN LATERAL (SELECT
  (ARRAY['HOME_SAMPLE','HOME_SAMPLE','HOME_SAMPLE','CENTER_VISIT','CAMP']::"OrderType"[])[1 + (x.k % 5)]
) t(order_type)
CROSS JOIN LATERAL (SELECT (ARRAY[
  'REPORT_DELIVERED','SAMPLE_PROCESSED','REPORT_DELIVERED','ORDER_SCHEDULED',
  'REPORT_DELIVERED','SAMPLE_COLLECTED','CANCELED','REPORT_DELIVERED',
  'PHLEBO_ASSIGNED','REPORT_DELIVERED','SAMPLE_PROCESSED','REPORT_DELIVERED',
  'RESCHEDULED','SAMPLE_COLLECTED','REPORT_DELIVERED','PENDING',
  'REPORT_DELIVERED','SAMPLE_DELIVERED','PATIENT_MISSED','REPORT_DELIVERED',
  'ORDER_SCHEDULED']::"OrderStatus"[])[1 + (x.k % 21)]
) s(status)
CROSS JOIN LATERAL (
  -- Age follows the stage, because a book where a quarter of the pending
  -- orders are eleven months old is not a book anybody would recognise, and
  -- it would have made the delayed count meaningless — everything would be
  -- delayed, so nothing would stand out.
  --
  --   finished or cancelled  →  anywhere in the last year
  --   sample in flight       →  collected in the last day or two, with a
  --                             quarter stretching back a fortnight
  --   waiting on a date      →  mostly the coming week, with a fifth that
  --                             has genuinely stalled
  --
  -- The tails are deliberately minorities. An earlier version spread the open
  -- orders evenly over a fortnight, which made 57% of the whole book count as
  -- delayed — every store red, the alert meaningless, and no way to tell a
  -- working page from a broken one. Delayed has to be the exception here for
  -- the same reason it is the exception in a real book.
  SELECT c.created_at,
         c.created_at + interval '10 hours' AS appointment_at,
         -- When the order last moved. For a delivered one that is when the
         -- report landed, and it is what turnaround is measured to — so it
         -- has to be a real interval after the booking, not a copy of it.
         -- Clamped to now(): an order that has not happened yet cannot have
         -- been updated after it, and a future timestamp here would have made
         -- every average negative.
         GREATEST(c.created_at,
                  LEAST(c.created_at + interval '10 hours'
                          + ((6 + (x.k % 66)) || ' hours')::interval,
                        now())) AS status_at
  FROM (SELECT now() - ((CASE
          WHEN s.status IN ('REPORT_DELIVERED','CANCELED','PATIENT_MISSED') THEN (x.k % 365)
          WHEN s.status IN ('SAMPLE_COLLECTED','SAMPLE_DELIVERED','SAMPLE_PROCESSED',
                            'PATIENT_VISITED')
            THEN CASE WHEN x.k % 4 = 0 THEN 3 + (x.k % 11) ELSE (x.k % 2) END
          -- Negative is an appointment still ahead, which is most of them.
          ELSE CASE WHEN x.k % 5 = 0 THEN 4 + (x.k % 15) ELSE (x.k % 9) - 6 END
        END) || ' days')::interval AS created_at) c
) d
CROSS JOIN LATERAL (
  -- A phlebo, but only where there would be one: somebody has to be sent to a
  -- home collection, nobody is sent to a centre visit, and the assignment has
  -- not happened yet while the order is still waiting on a date.
  SELECT CASE WHEN t.order_type = 'HOME_SAMPLE'
                AND s.status NOT IN ('PENDING','CREATED','ORDER_SCHEDULED','RESCHEDULED')
              THEN (ARRAY['Anil Kumar','Pooja Shetty','Imran Qureshi','Lata Deshmukh',
                          'Rohit Varma','Sneha Pillai','Tarun Ghosh','Kavya Reddy',
                          'Mohan Das','Ritika Jain','Salim Ansari','Nisha Thomas'])[1 + (x.k % 12)]
         END,
         CASE WHEN t.order_type = 'HOME_SAMPLE'
                AND s.status NOT IN ('PENDING','CREATED','ORDER_SCHEDULED','RESCHEDULED')
              THEN '97' || lpad((2000000 + x.k * 13)::text, 8, '0')
         END,
         CASE WHEN t.order_type = 'HOME_SAMPLE'
                AND s.status NOT IN ('PENDING','CREATED','ORDER_SCHEDULED','RESCHEDULED')
              THEN d.created_at + interval '4 hours'
         END,
         CASE WHEN t.order_type = 'HOME_SAMPLE'
                AND s.status NOT IN ('PENDING','CREATED','ORDER_SCHEDULED','RESCHEDULED')
              THEN 'dispatch-console'
         END
) ph(name, phone, assigned_at, assigned_by);

-- ---------------------------------------------------------------------------
-- Requests: demand that has not become an order yet. The /requests queue reads
-- these, so a few are deliberately left open and unserviceable.
-- ---------------------------------------------------------------------------
INSERT INTO "Request" (id, name, mobile, email, address, locality, city, state, pincode,
                       gender, source, status, priority, "orderType", "storeId", "labId",
                       "isConverted", "isServiceable", "createdAt", "updatedAt",
                       "preferredDateTime", notes)
SELECT g, 'Requester ' || g, '97000' || lpad(g::text, 5, '0'),
       'requester' || g || '@example.test',
       g || ', Enquiry Street', 'Zone ' || (1 + g % 7), a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       (ARRAY['MALE','FEMALE','OTHERS']::"Gender"[])[1 + (g % 3)],
       (ARRAY['WEBSITE','STORE','QR_CODE','SOCIAL_MEDIA']::"RequestSource"[])[1 + (g % 4)],
       (ARRAY['OPEN','QUOTED','ORDERED','NON_SERVICEABLE','CANCELLED',
              'OPEN','QUOTATION_ACCEPTED']::"RequestStatus"[])[1 + (g % 7)],
       (ARRAY['LOW','MEDIUM','HIGH']::"Priority"[])[1 + (g % 3)],
       (ARRAY['HOME_SAMPLE','CENTER_VISIT']::"OrderType"[])[1 + (g % 2)],
       1 + (g % 8),
       CASE WHEN g % 7 = 2 THEN 1 + (g % (SELECT COUNT(*) FROM "Lab"))::int ELSE NULL END,
       (g % 7 = 2), (g % 7 <> 3),
       now() - ((g % 60) || ' days')::interval, now() - ((g % 60) || ' days')::interval,
       now() + interval '1 day', 'Seeded enquiry'
FROM generate_series(1, 120) g
CROSS JOIN LATERAL (SELECT * FROM city_anchor ORDER BY (g * 19) % 10 LIMIT 1 OFFSET (g % 10)) a;

-- Which request became which order.
--
-- "Request"."isConverted" was set above and "convertedOrderId" never was, so
-- the link was a flag with nothing on the other end. analytics.v_request_order
-- joins Order to Request through exactly that column, and every queue on
-- /order-tracking derives from it — which means all three came up empty on a
-- fresh machine whatever the data said, and the page could not be checked at
-- all. Same shape as the request-item gap: the rows existed and the join
-- between them did not.
--
-- Paired by rank within a store so no two requests claim the same order, and
-- drawn from the orders still in flight, because an order that has already
-- been delivered is not work anybody is tracking.
WITH conv AS (
  SELECT id, "storeId",
         row_number() OVER (PARTITION BY "storeId" ORDER BY id) AS rn
  FROM "Request" WHERE "isConverted"
), cand AS (
  SELECT id, "storeId",
         row_number() OVER (PARTITION BY "storeId" ORDER BY "appointmentTime" DESC) AS rn
  FROM "Order"
  WHERE "orderStatus" NOT IN ('REPORT_DELIVERED', 'CANCELED', 'PATIENT_MISSED')
)
UPDATE "Request" r
   SET "convertedOrderId" = cand.id
  FROM conv JOIN cand ON cand."storeId" = conv."storeId" AND cand.rn = conv.rn
 WHERE r.id = conv.id;

-- The same link from the other side, which is the column the stores screen
-- reads to say an order came from a request rather than straight from a store.
UPDATE "Order" o
   SET "requestId" = r.id
  FROM "Request" r
 WHERE r."convertedOrderId" = o.id;

-- ---------------------------------------------------------------------------
-- The catalogue: tests, the packages they sit in, and what each lab charges.
-- ---------------------------------------------------------------------------
INSERT INTO "Master" (id, "lsId", name, "testCategory", hsc, "isTestProfile", "fastingNeeded",
                      "subTests", "createdAt", "updatedAt")
SELECT g, 'LS-M-' || lpad(g::text, 4, '0'),
       (ARRAY['Complete Blood Count','Lipid Profile','Liver Function Test','Thyroid Profile',
              'HbA1c','Vitamin D','Vitamin B12','Serum Creatinine','Urine Routine',
              'Kidney Function Test','Iron Studies','CRP','Blood Sugar Fasting',
              'Blood Sugar PP','Uric Acid'])[1 + (g % 15)] || CASE WHEN g > 15 THEN ' (Panel ' || g || ')' ELSE '' END,
       (ARRAY['ROUTINE','ROUTINE','NON_ROUTINE']::"TestCategory"[])[1 + (g % 3)],
       (g % 2 = 0), (g % 5 = 0), (g % 4 = 0),
       CASE WHEN g % 5 = 0 THEN ARRAY['Sub A', 'Sub B'] ELSE NULL END,
       now() - interval '2 years', now()
FROM generate_series(1, 60) g;

INSERT INTO "Package" (id, "lsId", "packageName", active, "isCustom", "orderTypes",
                       "defaultTat", "createdAt", "updatedAt")
SELECT g, 'LS-P-' || lpad(g::text, 4, '0'),
       (ARRAY['Basic Health Check','Full Body Check','Diabetes Panel','Heart Care Panel',
              'Women''s Wellness','Senior Citizen Panel','Fever Panel','Pre-Employment Panel'])[1 + (g % 8)]
         || ' ' || g,
       true, (g % 6 = 0),
       ARRAY['HOME_SAMPLE','CENTER_VISIT']::"OrderType"[],
       24, now() - interval '1 year', now()
FROM generate_series(1, 30) g;

INSERT INTO "_MasterToPackage" ("A", "B")
SELECT DISTINCT 1 + ((p * 7 + m) % 60), p
FROM generate_series(1, 30) p, generate_series(1, 5) m;

-- What each lab charges for each package it carries. Prices drift by lab, so
-- the pricing page has something to compare.
INSERT INTO "PackagesOnLab" ("labId", "packageId", "labCost", "labMrp", "labPackageName",
                             "assignedAt", "assignedBy", "createdAt", "updatedAt")
SELECT l.id, p.id,
       (300 + ((l.id * 37 + p.id * 11) % 1200))::int,
       (300 + ((l.id * 37 + p.id * 11) % 1200)) * 1.6,
       'Pkg ' || p.id || ' @ Lab ' || l.id,
       now() - interval '6 months', 'seed', now() - interval '6 months', now()
FROM "Lab" l JOIN "Package" p ON (l.id + p.id) % 3 <> 0;

INSERT INTO "DOS" (id, "dosID", "labTestName", master_id, price, "labCost", "turnAroundTime",
                   "nablCertified", active, "inHouse", lab_id, "createdAt", "updatedAt")
SELECT row_number() OVER ()::int,
       'DOS-' || l.id || '-' || m.id,
       m.name, m.id,
       (150 + ((l.id * 13 + m.id * 7) % 900))::float,
       (100 + ((l.id * 11 + m.id * 5) % 600))::float,
       24, (l.id % 3 <> 0), true, (m.id % 4 <> 0), l.id,
       now() - interval '6 months', now()
FROM "Lab" l JOIN "Master" m ON (l.id + m.id) % 4 <> 0;

-- ---------------------------------------------------------------------------
-- Which labs and packages each store can actually sell.
-- ---------------------------------------------------------------------------
INSERT INTO "LabsOnStore" ("storeId", "labId", "storeLabRanking", "assignedAt", "assignedBy", "createdAt", "updatedAt")
SELECT s.id, l.id, 1 + (l.id % 3), now() - interval '3 months', 'seed', now() - interval '3 months', now()
FROM "Store" s JOIN "Lab" l ON (s.id + l.id) % 3 = 0;

INSERT INTO "PackagesOnStore" ("storeId", "packageId", "storePrice", "storeMrp", "assignedAt", "assignedBy",
                               "createdAt", "updatedAt")
SELECT s.id, p.id, (500 + ((s.id * 31 + p.id * 17) % 1500))::int,
       (900 + ((s.id * 31 + p.id * 17) % 1500))::int,
       now() - interval '3 months', 'seed', now() - interval '3 months', now()
FROM "Store" s JOIN "Package" p ON (s.id + p.id) % 4 = 0;

-- ---------------------------------------------------------------------------
-- Teleconsults and pharmacy orders — thin, but the demand views join them.
-- ---------------------------------------------------------------------------
INSERT INTO "Appointment" (id, user_id, "createdAt", "updatedAt")
SELECT g, 1 + (g % 400), now() - ((g % 200) || ' days')::interval, now()
FROM generate_series(1, 150) g;

INSERT INTO "PharmaOrder" (id, "userId", "createdAt", "updatedAt")
SELECT g, 1 + (g % 400), now() - ((g % 200) || ' days')::interval, now()
FROM generate_series(1, 90) g;

COMMIT;

ANALYZE;
