-- ============================================================================
-- A small, invented LabStack — enough for every Atlas page to have something
-- to show.
--
-- None of this is real. The cities, their coordinates and the pincode ranges
-- are public geography; every lab, doctor, patient, order and price below was
-- generated by the SQL in this file. No LabStack data is in this repository
-- and none should ever be committed to it — if you need real data locally,
-- point at the source database instead (docs/LOCAL-SETUP.md).
--
-- Deterministic: setseed() fixes the sequence, so two developers running this
-- get the same rows and can compare numbers with each other.
--
-- Re-runnable: truncates before it inserts.
-- ============================================================================

SET search_path = src_local, public;

-- One transaction: the temp tables below are ON COMMIT DROP, and psql commits
-- after every statement unless told otherwise — without this the first temp
-- table is gone before the insert that fills it.
BEGIN;
SELECT setseed(0.42);

TRUNCATE "Lab", "Chain", "Provider", "ProviderType", "Pharmacy", "Store",
         "PincodeToLatLong", "User", "Profile", "Order", "Request",
         "Master", "Package", "PackagesOnLab", "DOS", "_MasterToPackage",
         "_MasterToRequest", "_PackageToRequest", "PackagesOnStore",
         "LabsOnStore", "Appointment", "PharmaOrder";

-- ---------------------------------------------------------------------------
-- Geography. Ten real cities, a made-up block of pincodes around each.
--
-- Two metros, two large cities and six smaller ones, because the readiness and
-- tiering pages exist to tell those apart and a seed of ten metros would make
-- every one of them say the same thing.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE city_anchor (city text, state text, pin_base int, lat float, lng float, labs int) ON COMMIT DROP;
INSERT INTO city_anchor VALUES
  ('Mumbai',    'Maharashtra',    400001, 19.0760, 72.8777, 9),
  ('Delhi',     'Delhi',          110001, 28.6139, 77.2090, 8),
  ('Bengaluru', 'Karnataka',      560001, 12.9716, 77.5946, 7),
  ('Pune',      'Maharashtra',    411001, 18.5204, 73.8567, 5),
  ('Hyderabad', 'Telangana',      500001, 17.3850, 78.4867, 5),
  ('Jaipur',    'Rajasthan',      302001, 26.9124, 75.7873, 3),
  ('Indore',    'Madhya Pradesh', 452001, 22.7196, 75.8577, 3),
  ('Kochi',     'Kerala',         682001, 9.9312,  76.2673, 2),
  ('Guwahati',  'Assam',          781001, 26.1445, 91.7362, 2),
  ('Nagpur',    'Maharashtra',    440001, 21.1458, 79.0882, 2);

-- Eight pincodes per city, spread over roughly 12 km.
INSERT INTO "PincodeToLatLong" (id, pincode, latitude, longitude, city, state, district)
SELECT row_number() OVER ()::int,
       lpad((a.pin_base + g)::text, 6, '0'),
       a.lat + (g - 4) * 0.012,
       a.lng + (g - 4) * 0.013,
       a.city, a.state, a.city
FROM city_anchor a, generate_series(0, 7) g;

-- ---------------------------------------------------------------------------
-- Chains and labs.
-- ---------------------------------------------------------------------------
INSERT INTO "Chain" (id, "chainName", name, "createdAt", "updatedAt") VALUES
  (1, 'Northwind Diagnostics', 'Northwind Diagnostics', now() - interval '3 years', now()),
  (2, 'Silverleaf Labs',       'Silverleaf Labs',       now() - interval '2 years', now()),
  (3, 'Cedarcare Group',       'Cedarcare Group',       now() - interval '18 months', now()),
  (4, 'Bluewater Health',      'Bluewater Health',      now() - interval '1 year', now());

CREATE TEMP TABLE lab_word (w text) ON COMMIT DROP;
INSERT INTO lab_word VALUES ('Northwind'),('Silverleaf'),('Cedarcare'),('Bluewater'),
  ('Greenfield'),('Harbour'),('Summit'),('Orchid'),('Lakeside'),('Ironbridge'),
  ('Meadow'),('Redstone'),('Kingfisher'),('Amberton'),('Fairview');

WITH numbered AS (
  SELECT a.*, generate_series(1, a.labs) AS n,
         row_number() OVER (ORDER BY a.city, generate_series(1, a.labs)) AS id
  FROM city_anchor a
)
INSERT INTO "Lab" (
  id, "labName", "centerType", chain_id, address, locality, city, state, pincode,
  active, latitude, longitude, "pincodesServiced", "homeCollection", "centerVisit",
  "createdAt", "updatedAt", "labCenterEmail", "labCenterMobile", "gstNumber",
  "mouStartDate", "mouEndDate"
)
SELECT
  n.id,
  (SELECT w FROM lab_word ORDER BY (n.id * 7 + n.n) % 15 LIMIT 1)
    || CASE n.n % 3 WHEN 0 THEN ' Diagnostics' WHEN 1 THEN ' Path Lab' ELSE ' Health Centre' END
    || ' · ' || n.city,
  (ARRAY['DIAGNOSTIC_CENTER','COLLECTION_CENTER','HOSPITAL']::"CenterType"[])[1 + (n.n % 3)],
  CASE WHEN n.n % 4 = 0 THEN 1 + (n.id % 4) ELSE NULL END,
  n.n || ', Sample Road', 'Block ' || chr(65 + (n.n % 6)), n.city, n.state,
  lpad((n.pin_base + (n.n % 8))::text, 6, '0'),
  true,
  n.lat + ((n.n % 8) - 4) * 0.012 + (random() - 0.5) * 0.004,
  n.lng + ((n.n % 8) - 4) * 0.013 + (random() - 0.5) * 0.004,
  -- Home collection reaches a handful of nearby pincodes; a centre-only lab
  -- serves none, which is what makes the two coverage numbers differ.
  CASE WHEN n.n % 4 <> 3
       THEN (SELECT array_agg(lpad((n.pin_base + g)::text, 6, '0'))
               FROM generate_series(0, 7) g WHERE g <= 3 + (n.n % 4))
       ELSE NULL END,
  (n.n % 4 <> 3),
  (n.n % 5 <> 4),
  now() - ((n.id * 13) || ' days')::interval,
  now() - ((n.id) || ' days')::interval,
  'ops' || n.id || '@example.test',
  '90000' || lpad(n.id::text, 5, '0'),
  '27AAAAA' || lpad(n.id::text, 4, '0') || 'A1Z5',
  now() - interval '1 year', now() + interval '1 year'
FROM numbered n;

-- ---------------------------------------------------------------------------
-- Providers: the people, not the buildings.
-- ---------------------------------------------------------------------------
INSERT INTO "ProviderType" (id, "typeName") VALUES
  (1, 'Doctor'), (2, 'Phlebotomist'), (3, 'Nurse'), (4, 'Physiotherapist');

INSERT INTO "Provider" (id, name, "typeId", address, locality, city, state, pincode,
                        latitude, longitude, mobile, email, "registrationBody",
                        "registrationNum", "isVerified", "experienceStart",
                        active, "createdAt", "updatedAt")
SELECT g,
       (ARRAY['Dr. A. Menon','Dr. S. Iyer','Dr. R. Bose','P. Kulkarni','N. Sharma',
              'V. Das','M. Pillai','K. Reddy','J. Fernandes','T. Ahuja'])[1 + (g % 10)]
         || ' (' || g || ')',
       1 + (g % 4),
       g || ', Clinic Lane', 'Sector ' || (1 + g % 9), a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       a.lat + ((g % 8) - 4) * 0.012, a.lng + ((g % 8) - 4) * 0.013,
       '98000' || lpad(g::text, 5, '0'), 'provider' || g || '@example.test',
       CASE WHEN g % 4 <> 0 THEN 'State Council' END,
       CASE WHEN g % 4 <> 0 THEN 'REG-' || lpad(g::text, 5, '0') END,
       (g % 3 <> 0),
       now() - ((3 + (g % 15)) || ' years')::interval,
       true, now() - ((g * 5) || ' days')::interval, now()
FROM generate_series(1, 60) g
CROSS JOIN LATERAL (
  SELECT * FROM city_anchor ORDER BY (g * 31) % 10 LIMIT 1 OFFSET (g % 10)
) a;

INSERT INTO "Pharmacy" (id, name, address, city, state, pincode, latitude, longitude,
                        active, "createdAt", "updatedAt")
SELECT g,
       (ARRAY['Wellspring','Cornerstone','Gracewell','Apex','Sunrise'])[1 + (g % 5)] || ' Pharmacy ' || g,
       g || ', Market Street', a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       a.lat + ((g % 8) - 4) * 0.012, a.lng + ((g % 8) - 4) * 0.013,
       true, now() - ((g * 9) || ' days')::interval, now()
FROM generate_series(1, 14) g
CROSS JOIN LATERAL (SELECT * FROM city_anchor ORDER BY (g * 17) % 10 LIMIT 1 OFFSET (g % 10)) a;

-- ---------------------------------------------------------------------------
-- Stores: the B2B partners orders arrive from.
-- ---------------------------------------------------------------------------
INSERT INTO "Store" (id, "storeName", "legalName", "storeType", address, locality, city, state,
                     pincode, active, "apiEnabled", "createdAt", "updatedAt", "isDoctor")
SELECT g,
       (ARRAY['Riverbend Clinic','Parkview Polyclinic','Trailhead Wellness','Stonegate Care',
              'Maple Health','Eastfield Clinic','Fernway Medical','Harbourside Care'])[g],
       (ARRAY['Riverbend','Parkview','Trailhead','Stonegate','Maple','Eastfield','Fernway','Harbourside'])[g] || ' Pvt Ltd',
       CASE WHEN g % 3 = 0 THEN 'CLINIC' ELSE 'CORPORATE' END,
       g || ', Partner Avenue', 'Phase ' || g, a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       true, (g % 2 = 0), now() - ((g * 40) || ' days')::interval, now(), (g % 3 = 0)
FROM generate_series(1, 8) g
CROSS JOIN LATERAL (SELECT * FROM city_anchor ORDER BY (g * 23) % 10 LIMIT 1 OFFSET (g % 10)) a;

-- ---------------------------------------------------------------------------
-- Patients. A user and the profile carrying the address an order is served at.
-- ---------------------------------------------------------------------------
INSERT INTO "User" (id, email, phone, name, "createdAt", "updatedAt")
SELECT g, 'patient' || g || '@example.test', '99000' || lpad(g::text, 5, '0'),
       'Patient ' || g, now() - ((g % 500) || ' days')::interval, now()
FROM generate_series(1, 400) g;

INSERT INTO "Profile" (id, "profileUserId", name, gender, dob, address, locality, city, state,
                       pincode, latitude, longitude, "createdAt", "updatedAt")
SELECT g, g, 'Patient ' || g,
       (ARRAY['MALE','FEMALE','OTHERS']::"Gender"[])[1 + (g % 3)],
       now() - ((20 + (g % 50)) || ' years')::interval,
       g || ', Residency Road', 'Ward ' || (1 + g % 12), a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       -- Scattered around the pincode, because the geo rebuild takes the
       -- median of the addresses it has seen there.
       a.lat + ((g % 8) - 4) * 0.012 + (random() - 0.5) * 0.006,
       a.lng + ((g % 8) - 4) * 0.013 + (random() - 0.5) * 0.006,
       now() - ((g % 500) || ' days')::interval, now()
FROM generate_series(1, 400) g
CROSS JOIN LATERAL (SELECT * FROM city_anchor ORDER BY (g * 11) % 10 LIMIT 1 OFFSET (g % 10)) a;

-- ---------------------------------------------------------------------------
-- Orders across the last year, weighted the way a real book is: mostly home
-- collection, mostly delivered, a tail of cancellations.
-- ---------------------------------------------------------------------------
-- Weighted by city, because a leaderboard where every city has the same number
-- is no test of a leaderboard. Roughly six orders in Mumbai for every one in
-- Guwahati, which is the shape of the real book.
CREATE TEMP TABLE city_weight (city text, w int) ON COMMIT DROP;
INSERT INTO city_weight VALUES
  ('Mumbai', 6), ('Delhi', 5), ('Bengaluru', 5), ('Hyderabad', 4), ('Pune', 3),
  ('Jaipur', 2), ('Indore', 2), ('Kochi', 2), ('Nagpur', 1), ('Guwahati', 1);

INSERT INTO "Order" (id, "orderType", "orderStatus", "storeId", "labId", "userId",
                     "createdAt", "updatedAt", "appointmentTime", "isPostpaid", source)
SELECT row_number() OVER ()::int AS id,
       (ARRAY['HOME_SAMPLE','HOME_SAMPLE','HOME_SAMPLE','CENTER_VISIT','CAMP']::"OrderType"[])[1 + (x.k % 5)],
       (ARRAY['REPORT_DELIVERED','REPORT_DELIVERED','REPORT_DELIVERED','SAMPLE_PROCESSED',
              'SAMPLE_COLLECTED','ORDER_SCHEDULED','CANCELED']::"OrderStatus"[])[1 + (x.k % 7)],
       1 + (x.k % 8),
       -- Served by a lab in the same city where there is one, which is what
       -- makes the coverage and imbalance views say anything at all.
       COALESCE(
         (SELECT l.id FROM "Lab" l WHERE l.city = x.city ORDER BY (l.id + x.k) % 97 LIMIT 1),
         1 + (x.k % 40)),
       x.uid,
       now() - ((x.k % 365) || ' days')::interval,
       now() - ((x.k % 365) || ' days')::interval,
       now() - ((x.k % 365) || ' days')::interval + interval '10 hours',
       (x.k % 4 = 0),
       'STORE_API'::"Source"
FROM (
  SELECT p."profileUserId" AS uid, p.city,
         row_number() OVER (ORDER BY p.id, g) AS k
  FROM "Profile" p
  JOIN city_weight w ON w.city = p.city
  CROSS JOIN LATERAL generate_series(1, w.w) g
) x;

-- ---------------------------------------------------------------------------
-- Requests: demand that has not become an order yet. The /requests queue reads
-- these, so a few are deliberately left open and unserviceable.
-- ---------------------------------------------------------------------------
INSERT INTO "Request" (id, name, mobile, email, address, locality, city, state, pincode,
                       gender, source, status, priority, "orderType", "storeId", "labId",
                       "isConverted", "isServiceable", "createdAt", "updatedAt",
                       "preferredDateTime", notes)
SELECT g, 'Requester ' || g, '97000' || lpad(g::text, 5, '0'),
       'requester' || g || '@example.test',
       g || ', Enquiry Street', 'Zone ' || (1 + g % 7), a.city, a.state,
       lpad((a.pin_base + (g % 8))::text, 6, '0'),
       (ARRAY['MALE','FEMALE','OTHERS']::"Gender"[])[1 + (g % 3)],
       (ARRAY['WEBSITE','STORE','QR_CODE','SOCIAL_MEDIA']::"RequestSource"[])[1 + (g % 4)],
       (ARRAY['OPEN','QUOTED','ORDERED','NON_SERVICEABLE','CANCELLED',
              'OPEN','QUOTATION_ACCEPTED']::"RequestStatus"[])[1 + (g % 7)],
       (ARRAY['LOW','MEDIUM','HIGH']::"Priority"[])[1 + (g % 3)],
       (ARRAY['HOME_SAMPLE','CENTER_VISIT']::"OrderType"[])[1 + (g % 2)],
       1 + (g % 8),
       CASE WHEN g % 7 = 2 THEN 1 + (g % (SELECT COUNT(*) FROM "Lab"))::int ELSE NULL END,
       (g % 7 = 2), (g % 7 <> 3),
       now() - ((g % 60) || ' days')::interval, now() - ((g % 60) || ' days')::interval,
       now() + interval '1 day', 'Seeded enquiry'
FROM generate_series(1, 120) g
CROSS JOIN LATERAL (SELECT * FROM city_anchor ORDER BY (g * 19) % 10 LIMIT 1 OFFSET (g % 10)) a;

-- ---------------------------------------------------------------------------
-- The catalogue: tests, the packages they sit in, and what each lab charges.
-- ---------------------------------------------------------------------------
INSERT INTO "Master" (id, "lsId", name, "testCategory", hsc, "isTestProfile", "fastingNeeded",
                      "subTests", "createdAt", "updatedAt")
SELECT g, 'LS-M-' || lpad(g::text, 4, '0'),
       (ARRAY['Complete Blood Count','Lipid Profile','Liver Function Test','Thyroid Profile',
              'HbA1c','Vitamin D','Vitamin B12','Serum Creatinine','Urine Routine',
              'Kidney Function Test','Iron Studies','CRP','Blood Sugar Fasting',
              'Blood Sugar PP','Uric Acid'])[1 + (g % 15)] || CASE WHEN g > 15 THEN ' (Panel ' || g || ')' ELSE '' END,
       (ARRAY['ROUTINE','ROUTINE','NON_ROUTINE']::"TestCategory"[])[1 + (g % 3)],
       (g % 2 = 0), (g % 5 = 0), (g % 4 = 0),
       CASE WHEN g % 5 = 0 THEN ARRAY['Sub A', 'Sub B'] ELSE NULL END,
       now() - interval '2 years', now()
FROM generate_series(1, 60) g;

INSERT INTO "Package" (id, "lsId", "packageName", active, "isCustom", "orderTypes",
                       "defaultTat", "createdAt", "updatedAt")
SELECT g, 'LS-P-' || lpad(g::text, 4, '0'),
       (ARRAY['Basic Health Check','Full Body Check','Diabetes Panel','Heart Care Panel',
              'Women''s Wellness','Senior Citizen Panel','Fever Panel','Pre-Employment Panel'])[1 + (g % 8)]
         || ' ' || g,
       true, (g % 6 = 0),
       ARRAY['HOME_SAMPLE','CENTER_VISIT']::"OrderType"[],
       24, now() - interval '1 year', now()
FROM generate_series(1, 30) g;

INSERT INTO "_MasterToPackage" ("A", "B")
SELECT DISTINCT 1 + ((p * 7 + m) % 60), p
FROM generate_series(1, 30) p, generate_series(1, 5) m;

-- What each lab charges for each package it carries. Prices drift by lab, so
-- the pricing page has something to compare.
INSERT INTO "PackagesOnLab" ("labId", "packageId", "labCost", "labMrp", "labPackageName",
                             "assignedAt", "assignedBy", "createdAt", "updatedAt")
SELECT l.id, p.id,
       (300 + ((l.id * 37 + p.id * 11) % 1200))::int,
       (300 + ((l.id * 37 + p.id * 11) % 1200)) * 1.6,
       'Pkg ' || p.id || ' @ Lab ' || l.id,
       now() - interval '6 months', 'seed', now() - interval '6 months', now()
FROM "Lab" l JOIN "Package" p ON (l.id + p.id) % 3 <> 0;

INSERT INTO "DOS" (id, "dosID", "labTestName", master_id, price, "labCost", "turnAroundTime",
                   "nablCertified", active, "inHouse", lab_id, "createdAt", "updatedAt")
SELECT row_number() OVER ()::int,
       'DOS-' || l.id || '-' || m.id,
       m.name, m.id,
       (150 + ((l.id * 13 + m.id * 7) % 900))::float,
       (100 + ((l.id * 11 + m.id * 5) % 600))::float,
       24, (l.id % 3 <> 0), true, (m.id % 4 <> 0), l.id,
       now() - interval '6 months', now()
FROM "Lab" l JOIN "Master" m ON (l.id + m.id) % 4 <> 0;

-- ---------------------------------------------------------------------------
-- Which labs and packages each store can actually sell.
-- ---------------------------------------------------------------------------
INSERT INTO "LabsOnStore" ("storeId", "labId", "storeLabRanking", "assignedAt", "assignedBy", "createdAt", "updatedAt")
SELECT s.id, l.id, 1 + (l.id % 3), now() - interval '3 months', 'seed', now() - interval '3 months', now()
FROM "Store" s JOIN "Lab" l ON (s.id + l.id) % 3 = 0;

INSERT INTO "PackagesOnStore" ("storeId", "packageId", "storePrice", "storeMrp", "assignedAt", "assignedBy",
                               "createdAt", "updatedAt")
SELECT s.id, p.id, (500 + ((s.id * 31 + p.id * 17) % 1500))::int,
       (900 + ((s.id * 31 + p.id * 17) % 1500))::int,
       now() - interval '3 months', 'seed', now() - interval '3 months', now()
FROM "Store" s JOIN "Package" p ON (s.id + p.id) % 4 = 0;

-- ---------------------------------------------------------------------------
-- Teleconsults and pharmacy orders — thin, but the demand views join them.
-- ---------------------------------------------------------------------------
INSERT INTO "Appointment" (id, user_id, "createdAt", "updatedAt")
SELECT g, 1 + (g % 400), now() - ((g % 200) || ' days')::interval, now()
FROM generate_series(1, 150) g;

INSERT INTO "PharmaOrder" (id, "userId", "createdAt", "updatedAt")
SELECT g, 1 + (g % 400), now() - ((g % 200) || ' days')::interval, now()
FROM generate_series(1, 90) g;

COMMIT;

ANALYZE;
